1. Make a custom exception
2. Make a 2-d array and read and write it in a csv format

In [2]:
class NegativeDepositError(Exception):
    pass

amount = float(input("Enter the amount you want to deposit: "))

try:
    if amount < 0:
        raise NegativeDepositError("Deposit amount cannot be negative!")
    else:
        print(f"₹{amount} deposited successfully!")

except NegativeDepositError as e:
    print("Caught Custom Exception:", e)

Caught Custom Exception: Deposit amount cannot be negative!


In [ ]:
import numpy as np
import csv

ar = np.array([
    [100, 200, 300],
    [400, 500, 600],
    [700, 800, 900]
])
 
with open("my_arr.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(ar)
print("Data write successfull...")

with open("my_arr.csv", "r") as f:
    reader = csv.reader(f)
    loaded_array = np.array([[int(value) for value in row] for row in reader])

print("2D Array read from CSV file")
print(loaded_array)

Data write successfull'
2D Array read from CSV file
[[100 200 300]
 [400 500 600]
 [700 800 900]]
