In [1]:
import numpy as np

Task 1: Creating Arrays
1. Write a Python program to: 
    o Create a 1D NumPy array of 10 integers ranging from 1 to 10.
    o Create a 2D NumPy array of shape (3, 3) with integers from 1 to 9.
    o Create a 3D NumPy array with random floating-point numbers of shape (3, 5, 3).
2. Display the shape, size, and datatype of each array.

In [2]:
OneD_Array = np.arange(1,11)
print(OneD_Array, type(OneD_Array), OneD_Array.shape, OneD_Array.size, OneD_Array.dtype)
print("-"*40)


TwoD_Array = np.random.randint(1, 10, size=(3,3))
print(TwoD_Array, type(TwoD_Array), TwoD_Array.shape, TwoD_Array.size, TwoD_Array.dtype)
print("-"*40)


ThreeD_Array = np.random.rand(3,5,3)
print(ThreeD_Array, type(ThreeD_Array), ThreeD_Array.shape, ThreeD_Array.size, ThreeD_Array.dtype)
print("-"*40)

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,) 10 int32
----------------------------------------
[[5 1 9]
 [2 3 2]
 [4 6 7]] <class 'numpy.ndarray'> (3, 3) 9 int32
----------------------------------------
[[[0.58596651 0.68306462 0.81885709]
  [0.94918868 0.55053741 0.88965277]
  [0.65851719 0.72690881 0.68109264]
  [0.34635391 0.34111542 0.39804689]
  [0.59001183 0.75127798 0.44651796]]

 [[0.9045708  0.17526859 0.35162873]
  [0.74502128 0.61632807 0.02568618]
  [0.25250874 0.55626229 0.24962137]
  [0.99338693 0.66788968 0.48546989]
  [0.89551749 0.39680994 0.76854622]]

 [[0.6015399  0.50105138 0.97717105]
  [0.482597   0.76523359 0.12544379]
  [0.45779396 0.8458716  0.51222368]
  [0.21268004 0.25628771 0.99131636]
  [0.88332903 0.11139138 0.78733568]]] <class 'numpy.ndarray'> (3, 5, 3) 45 float64
----------------------------------------


Task 2: Array Indexing and Slicing
1. Create a NumPy array from the following list: 
    data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
2. Write a Python program to: 
    o Retrieve the first three elements of the array.
    o Retrieve every alternate element of the array.
    o Reverse the array.
3. Perform the above operations and display the results.

In [3]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
arr = np.array(data)
print(arr, type(arr))

first_3_elements = arr[:3]
print(first_3_elements)

alternate_elements = arr[::2]
print(alternate_elements)

reverse_elements = arr[::-1]
print(reverse_elements)

[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>
[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations
1. Create two NumPy arrays, A and B, each with 5 random integers 
between 1 and 20.
2. Write a Python program to: 
    o Add, subtract, multiply, and divide the two arrays element-wise.
    o Compute the dot product of the arrays.
    o Find the mean, median, standard deviation, and variance of array A.
    o Identify the maximum and minimum values in array B and their indices.


In [4]:
A = np.random.randint(1, 20, size=(5))
B = np.random.randint(1, 20, size=(5))

add = A + B
print('Addition : ',add)

subtract = A - B
print('Subtraction : ',subtract)

multiply = A * B
print('Multiplication : ',multiply)

divide = A / B
print('Division : ',divide)



dot_product = np.dot(A, B)
print('Dot product : ', dot_product)

mean = A.mean()
print('Mean : ',mean)

median = np.median(A)
print('Median : ',median)

std_deviation = np.std(A)
print(f"Standard Deviation: {std_deviation:.2f}")


variance = std_deviation ** 2
print(f"Variance : {variance:.2f}")


min = np.min(B)
min_index = np.argmin(B)
print("Min Element : ", min)
print("Min Element index: ", min_index)


max = np.max(B)
max_index = np.argmax(B)
print("Max Element : ", max)
print("Max Element index: ", max_index)

Addition :  [ 9 28 14 29 24]
Subtraction :  [  1   4 -10  -9  -4]
Multiplication :  [ 20 192  24 190 140]
Division :  [1.25       1.33333333 0.16666667 0.52631579 0.71428571]
Dot product :  566
Mean :  8.6
Median :  10.0
Standard Deviation: 4.80
Variance : 23.04
Min Element :  4
Min Element index:  0
Max Element :  19
Max Element index:  3


Task 4: Reshaping and Transposing
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to: 
o Reshape the array into a 2D array of shape (4, 3).
o Reshape the array into a 3D array of shape (2, 2, 3).
o Transpose the reshaped 2D array and display its shape.

In [6]:
arr1 = np.arange(1, 13)
print(arr1, type(arr1))


print("Reshape (4 x 3) : ")
print(arr1.reshape(4,3))


print("-"*40)
print("Reshape (2 x 2 x 3) : ")
print(arr1.reshape(2,2,3))

print("-"*40)


print("Transpose Matrix : ")
two_d = arr1.reshape(4,3)

transpose_2D = two_d.transpose()
print(transpose_2D)

[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
Reshape (4 x 3) : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------------------------------
Reshape (2 x 2 x 3) : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------------------------
Transpose Matrix : 
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Task 5: Boolean Masking and Filtering
1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to: 
o Find all elements greater than 25.
o Replace all elements less than 30 with 0.
o Count the number of elements divisible by 5.

In [7]:
arr1 = np.random.randint(10, 50, 15 )
print(arr1)
print("-"*40)


greater_than_25 = arr1[arr1 > 25]
print(greater_than_25)
print("-"*40)


arr1[arr1 < 30] = 0
print(arr1)
print("-"*40)

div_by_5 = arr1[arr1 % 5 == 0]
count = len(div_by_5)
print(count)

[31 44 41 10 48 10 15 16 41 33 41 41 37 44 47]
----------------------------------------
[31 44 41 48 41 33 41 41 37 44 47]
----------------------------------------
[31 44 41  0 48  0  0  0 41 33 41 41 37 44 47]
----------------------------------------
4


Task 6: Working with Built-in Functions
1. Use NumPy's built-in functions to: 
o Create an array of 10 equally spaced values between 0 and 1.
o Create an identity matrix of size 4x4.
o Generate a 1D array of 20 random integers between 1 and 100, 
sort it, and find the 5 largest elements.

In [8]:
arr1 = np.linspace(0,1,10)
print(arr1)
print('-'*35)

print('Identity Matrix')
print('-'*35)
print(np.eye(4, dtype=int))

print('-'*35)

one_D = np.random.randint(1, 100, 20)
print("Original Array : ",one_D)
print('-'*35)
sortArr = np.sort(one_D)
print("Sorted Array : ",sortArr)
print('-'*35)

print("Largest 5 element in array : ",sortArr[-5:])
print('-'*35)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
-----------------------------------
Identity Matrix
-----------------------------------
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
-----------------------------------
Original Array :  [63 53 51 48 87 37 49  5 82 95 74 43 18 76 88 36 68  2 87  3]
-----------------------------------
Sorted Array :  [ 2  3  5 18 36 37 43 48 49 51 53 63 68 74 76 82 87 87 88 95]
-----------------------------------
Largest 5 element in array :  [82 87 87 88 95]
-----------------------------------


Task 7: Generic
1. Create a Python program that: 
o Generates two large random arrays of size (100, 100).
o Performs matrix multiplication on the two arrays.
o Finds the determinant and inverse of the resulting matrix (if 
possible).
o Measures the time taken to complete these operations.


In [10]:
import numpy as np
import time

A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

start = time.time()

C = np.dot(A, B)
dete = np.linalg.det(C)

if not np.isclose(dete, 0):
    inv = np.linalg.inv(C)
    print("Inverse Matrix:\n", inv)
else:
    print("Matrix is not invertible")
print('-'*35)
end = time.time()
print("Determinant:", dete)
print('-'*35)
print("Time taken:", end - start, "seconds")
print('-'*35)

Inverse Matrix:
 [[-1.32022846e+00  2.25209706e-01 -1.96249695e+00 ...  7.96427841e+00
   7.83660539e-01  2.31650593e+00]
 [ 4.90989610e-01 -6.73123041e-01  2.27623806e+00 ... -7.44725730e+00
  -3.42953518e+00 -2.21319435e+00]
 [-1.90877675e+00 -5.95613106e-01 -2.38041971e+00 ...  3.28930733e+00
   6.68496429e-01  2.20692526e-01]
 ...
 [-4.78152334e+00  1.53159261e+00 -1.08839472e+01 ...  3.33985232e+01
   1.01543064e+01  9.54130361e+00]
 [ 2.31396222e+00 -2.54439459e-02  3.24362576e+00 ... -1.13188835e+01
  -2.19314564e+00 -3.41354924e+00]
 [ 3.21660843e-01 -5.95654111e-01  2.63178501e+00 ... -6.34220191e+00
  -3.28796812e+00 -1.72204769e+00]]
-----------------------------------
Determinant: -2.8522238880056235e+50
-----------------------------------
Time taken: 0.16768193244934082 seconds
-----------------------------------
